### PR TITLE
chore: update config.rs

### PR DESCRIPTION
**Pull request by Tinrii**
changed max upload file size value from 100MB to 20GB as it should be

**What this PR does** 📖
fixes what dev **ashneverdawn** wrote as note that i stated in this pull request
https://github.com/Satellite-im/UplinkWeb/pull/881
**Which issue(s) this PR fixes** 🔨
https://github.com/Satellite-im/UplinkWeb/pull/881

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Comment by dariusc93** [comment]
Hey! Thanks for the PR. 

I did leave a comment on https://github.com/Satellite-im/UplinkWeb/pull/881#issuecomment-2498942898 but in all I dont mind the change, but do keep in mind that it is set to 100MB as a balance between desktop/native (including mobile) and web/wasm. Additionally, it leaves room for additional files to be added before it hits the max storage limit. Also, we would not be able to set it beyond 2GB due to wasm32 address space target limit (see comment for more details). So if we are to set this value, it should be set to 2GB.

**Comment by Tinrii** [comment]
hello, i have changed it again and set it to 2GB instead of 20GB 😄

**Review by ashneverdawn — COMMENTED** [review]
I suggest following the pattern used by `max_storage_size`:
```Some(2 * 1024 * 1024 * 1024)```

**Comment by Tinrii** [comment]
updated 😄

**Pull request merged**
